
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Indunil Sensly
 */
public class Return extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Return
     */
    public Return() {
        super("Return Book");
        initComponents();
        con=DBConnection.getConnection();
    }
    
    public void Delete(){
        String sql="delete from Issue where Book_ID=?";
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1, jTextField7_book_id.getText());
            pst.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void ReturnUpdate(){
        String sql="insert into return_book(Student_ID,S_Name,Father_Name,Course,Branch,Year,Semester,Book_Id,B_Name,Edition,Publisher,Price,Pages,DOI,DOR) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";
        try{pst=con.prepareStatement(sql);
        pst.setString(1,jTextField1_studentId.getText());
        pst.setString(2,jTextField2_Sname.getText());
        pst.setString(3,jTextField3_fatherName.getText());
        pst.setString(4,jTextField4_course.getText());
        pst.setString(5,jTextField5_branch.getText());
        pst.setString(6,jTextField6_year.getText());
        pst.setString(7,jTextField8_semester.getText());
        pst.setString(8,jTextField7_book_id.getText());
        pst.setString(9,jTextField9_Bname.getText());
        pst.setString(10,jTextField10_Edition.getText());
        pst.setString(11,jTextField11_publisher.getText());
        pst.setString(12,jTextField12_price.getText());
        pst.setString(13,jTextField13_pages.getText());
        pst.setString(14,jTextField14_dateofisse.getText());
        pst.setString(15,jTextField15_returnDate.getText());
        pst.execute();
        
        JOptionPane.showMessageDialog(null,"Book Returned");
        
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField9_Bname = new javax.swing.JTextField();
        jTextField3_fatherName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6_year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7_book_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4_course = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField11_publisher = new javax.swing.JTextField();
        jTextField14_dateofisse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField13_pages = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2_Sname = new javax.swing.JTextField();
        jTextField10_Edition = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5_branch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8_semester = new javax.swing.JTextField();
        jTextField12_price = new javax.swing.JTextField();
        jTextField1_studentId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2_book_search = new javax.swing.JButton();
        jButton1_return = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField15_returnDate = new javax.swing.JTextField();
        jButton2_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 102, 0))); // NOI18N

        jLabel13.setText("Date of Isse");

        jLabel8.setText("Name");

        jLabel3.setText("Father Name");

        jLabel5.setText("Branch");

        jLabel2.setText("Name");

        jLabel1.setText("Student ID");

        jLabel7.setText("Book ID");

        jLabel6.setText("Year");

        jLabel11.setText("Price");

        jLabel12.setText("Pages");

        jLabel4.setText("Course");

        jLabel9.setText("Edition");

        jLabel10.setText("Publisher");

        jLabel14.setText("Semester");

        jButton2_book_search.setText("Search");
        jButton2_book_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_book_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_studentId)
                    .addComponent(jTextField2_Sname)
                    .addComponent(jTextField3_fatherName)
                    .addComponent(jTextField4_course)
                    .addComponent(jTextField5_branch)
                    .addComponent(jTextField6_year)
                    .addComponent(jTextField8_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7_book_id)
                    .addComponent(jTextField9_Bname)
                    .addComponent(jTextField10_Edition)
                    .addComponent(jTextField11_publisher)
                    .addComponent(jTextField12_price)
                    .addComponent(jTextField13_pages)
                    .addComponent(jTextField14_dateofisse, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton2_book_search)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_book_search))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2_Sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField9_Bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3_fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField10_Edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField11_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField12_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField13_pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField14_dateofisse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1_return.setText("Return");
        jButton1_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_returnActionPerformed(evt);
            }
        });

        jLabel15.setText("Return Date");

        jButton2_back.setText("Back");
        jButton2_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton1_return)
                .addGap(60, 60, 60)
                .addComponent(jButton2_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(47, 47, 47)
                .addComponent(jTextField15_returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1_return)
                        .addComponent(jButton2_back))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField15_returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(904, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_backActionPerformed
        setVisible(false);
        Home ob = new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2_backActionPerformed

    private void jButton2_book_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_book_searchActionPerformed
            String sql="select * from Issue where Book_ID=?";
            try{
                pst=con.prepareStatement(sql);
                pst.setString(1,jTextField7_book_id.getText());
                rs=pst.executeQuery();
                if(rs.next()){
                    String add1=rs.getString("B_Name");
                    jTextField9_Bname.setText(add1);
                    
                    String add2=rs.getString("Edition");
                    jTextField10_Edition.setText(add2);
                    
                    String add3=rs.getString("Publisher");
                    jTextField11_publisher.setText(add3);
                    
                    String add4=rs.getString("Price");
                    jTextField12_price.setText(add4);
                    
                    String add5=rs.getString("Pages");
                    jTextField13_pages.setText(add5);
                    
                    String add6=rs.getString("DateOfIssue");
                    jTextField14_dateofisse.setText(add6);
                    
                    String add7=rs.getString("S_name");
                    jTextField2_Sname.setText(add7);
                    
                    String add8=rs.getString("F_name");
                    jTextField3_fatherName.setText(add8);
                    
                    String add9=rs.getString("Course");
                    jTextField4_course.setText(add9);
                    
                    String add10=rs.getString("Branch");
                    jTextField5_branch.setText(add10);
                    
                    String add11=rs.getString("Year");
                    jTextField6_year.setText(add11);
                    
                    String add12=rs.getString("Semester");
                    jTextField8_semester.setText(add12);
                    
                    String add13 = rs.getString("Student_Id");
                    jTextField1_studentId.setText(add13);
                    
                    
                    rs.close();
                    pst.close();                   
                }else{
                    JOptionPane.showMessageDialog(null,"Book ID is not found ");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally{
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){
                    
                }
            }
                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_book_searchActionPerformed

    private void jButton1_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_returnActionPerformed
                Delete();
                ReturnUpdate();
    }//GEN-LAST:event_jButton1_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_return;
    private javax.swing.JButton jButton2_back;
    private javax.swing.JButton jButton2_book_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10_Edition;
    private javax.swing.JTextField jTextField11_publisher;
    private javax.swing.JTextField jTextField12_price;
    private javax.swing.JTextField jTextField13_pages;
    private javax.swing.JTextField jTextField14_dateofisse;
    private javax.swing.JTextField jTextField15_returnDate;
    private javax.swing.JTextField jTextField1_studentId;
    private javax.swing.JTextField jTextField2_Sname;
    private javax.swing.JTextField jTextField3_fatherName;
    private javax.swing.JTextField jTextField4_course;
    private javax.swing.JTextField jTextField5_branch;
    private javax.swing.JTextField jTextField6_year;
    private javax.swing.JTextField jTextField7_book_id;
    private javax.swing.JTextField jTextField8_semester;
    private javax.swing.JTextField jTextField9_Bname;
    // End of variables declaration//GEN-END:variables
}
